### DISCUSSION TITLE
How to create a scheduled event to execute a specific job?

### DISCUSSION THREAD

**Discussion by fabiensebban** [customink/lambdakiq#12] [Q&A] [answered]
I created a scheduled event in the `template.yaml` file but I don't know how to tell the schedule to run a specific job.
Someone knows how?

Here is the schedule I added to the Job resources:

```yaml
ScheduledEvent:
  Type: Schedule
  Properties:
    Schedule: cron(*/1 * * * ? *)
    Enabled: True
```

**Comment by metaskills** [comment, marked as answer]
YO! Sorry for the delayed response. Did you find an answer to your question? What you have above looks fine. Assuming you added that under the `Events:` property? 

Maybe too I should change this to a yes or maybe? https://github.com/customink/lambdakiq#common-questions

**Reply by fabiensebban** [reply]
Hey! It's OK. Thank you for your reply.
I did this in my `app.rb` file:
```ruby
ENV['RAILS_SERVE_STATIC_FILES'] = '1'
require_relative 'config/boot'
require 'dotenv' ; Dotenv.load ".env.#{ENV['RAILS_ENV']}"
require 'lamby'
require_relative 'config/application'
require_relative 'config/environment'

$app = Rack::Builder.new { run Rails.application }.to_app

def handler(event:, context:)
  if event['job_name']
    Object.const_get(event['job_name']).perform_later
  elsif Lambdakiq.jobs?(event)
    Lambdakiq.handler(event)
  else
    Lamby.handler $app, event, context, rack: :http
  end
end
```

And I created a schedule event adding this in `template.yml` under JobLambda -> Properties -> Events:
```YML
ScheduledEvent:
  Type: Schedule
  Properties:
    DeadLetterConfig: 
      Arn: !GetAtt JobsDLQueue.Arn
    Input: '{"job_name": "TheCronJob"}'
    Schedule: cron(*/1 * * * ? *)
    Enabled: True
```

It seems to work but I feel like it is not the correct way to get the job done. I will tell you if I find another way.
